language: objective-c
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script: xctool test -project DemoCodeCoverage/DemoCodeCoverage.xcodeproj/ -scheme DemoCodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
