language: objective-c
xcode_project: DemoCodeCoverage/DemoCodeCoverage.xcodeproj
xcode_scheme: DemoCodeCoverage
script: xctool test -project DemoCodeCoverage/DemoCodeCoverage.xcodeproj/ -scheme DemoCodeCoverage -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
